---
- name: Show Cisco
  hosts: Lakin-Correctional
  connection: ansible.netcommon.network_cli
  tasks:      
      
    - name: configurable backup path
      cisco.ios.ios_config:
        src: ios_template.j2
        backup: yes
      backup_options:
        filename: backup.cfg
        dir_path: /home/runner/backups
