---
- name: Show Cisco
  hosts: Lakin-Correctional
  connection: network_cli
  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config

   - name: save output to /etc/ansible/backups 
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/var/lib/awx/projects/backups/show_run_{{ inventory_hostname }}.txt"
       