---
- name: Show Cisco
  hosts: Lakin-Correctional
  connection: ansible.netcommon.network_cli
  tasks:
    - name: Get config for VyOS devices
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"